package GUI;

import BUS.BUS_SUA;
import BUS.LOADDULIEU;
import DAO.KiemTraLoi;
import DTO.NHANVIEN;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class FORM_NHANVIEN extends javax.swing.JFrame {

 
    public static ArrayList<NHANVIEN> listnv = new ArrayList<>();
    /**
     * Creates new form NhanVien
     */
    public FORM_NHANVIEN() {
        initComponents();
        HienLabel();
       
        
    }
    
    public void HienTextField()
    {
        txtHoTen.setVisible(true);
        txtNgaySinh.setVisible(true);
        txtSDT.setVisible(true);
        txtDiaChi.setVisible(true);
        txtEmail.setVisible(true);
        txtGioiTinh.setVisible(true);
        
        lbHoTen.setVisible(false);
        lb.setVisible(false);
        lbSDT.setVisible(false);
        lbDiaChi.setVisible(false);
        lbEmail.setVisible(false);
        lbGioiTinh.setVisible(false);
        
        btnCapNhat.setVisible(false);
        btnLuu.setVisible(true);
    }
    
    public void HienLabel()
    {
        lbHoTen.setVisible(true);
        lb.setVisible(true);
        lbSDT.setVisible(true);
        lbDiaChi.setVisible(true);
        lbEmail.setVisible(true);
        lbGioiTinh.setVisible(true);
        
        txtHoTen.setVisible(false);
        txtNgaySinh.setVisible(false);
        txtSDT.setVisible(false);
        txtDiaChi.setVisible(false);
        txtEmail.setVisible(false);
        txtGioiTinh.setVisible(false);
        
        btnCapNhat.setVisible(true);
        btnLuu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbMini = new javax.swing.JLabel();
        lbClose = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbHoTen = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        lbDiaChi = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JLabel();
        btnLuu = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JComboBox<>();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        lbNgaySinh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(47, 48, 48));

        jPanel2.setBackground(new java.awt.Color(61, 145, 106));
        jPanel2.setLayout(null);

        lbMini.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbMini.setForeground(new java.awt.Color(255, 255, 255));
        lbMini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMini.setText("-");
        lbMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMiniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMiniMouseExited(evt);
            }
        });
        jPanel2.add(lbMini);
        lbMini.setBounds(600, 0, 80, 50);

        lbClose.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbClose.setForeground(new java.awt.Color(255, 255, 255));
        lbClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbClose.setText("X");
        lbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCloseMousePressed(evt);
            }
        });
        jPanel2.add(lbClose);
        lbClose.setBounds(680, 0, 80, 50);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Thông Tin Nhân Viên");

        jPanel3.setBackground(new java.awt.Color(47, 48, 48));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã NV");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(200, 20, 100, 29);

        txtMaNV.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        txtMaNV.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtMaNV);
        txtMaNV.setBounds(330, 10, 149, 40);

        lb.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lb.setForeground(new java.awt.Color(255, 255, 255));
        lb.setText("Ngày Sinh");
        jPanel3.add(lb);
        lb.setBounds(30, 270, 85, 24);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Địa Chỉ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 370, 63, 24);

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });
        jPanel3.add(txtDiaChi);
        txtDiaChi.setBounds(130, 360, 188, 41);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Họ Tên");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(130, 100, 63, 24);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SĐT");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(400, 280, 38, 24);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(400, 370, 48, 24);

        txtHoTen.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel3.add(txtHoTen);
        txtHoTen.setBounds(240, 90, 300, 40);

        txtSDT.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        jPanel3.add(txtSDT);
        txtSDT.setBounds(490, 270, 190, 40);

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel3.add(txtEmail);
        txtEmail.setBounds(490, 360, 190, 40);

        lbHoTen.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbHoTen.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbHoTen);
        lbHoTen.setBounds(240, 90, 300, 40);

        lbSDT.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbSDT.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbSDT);
        lbSDT.setBounds(490, 270, 180, 40);

        lbDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbDiaChi.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbDiaChi);
        lbDiaChi.setBounds(130, 360, 190, 40);

        lbEmail.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbEmail);
        lbEmail.setBounds(490, 360, 190, 40);

        btnCapNhat.setBackground(new java.awt.Color(61, 145, 106));
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapNhat.setOpaque(true);
        btnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCapNhatMousePressed(evt);
            }
        });
        jPanel3.add(btnCapNhat);
        btnCapNhat.setBounds(240, 450, 120, 50);

        btnLuu.setBackground(new java.awt.Color(61, 145, 106));
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLuu.setText("Lưu");
        btnLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuu.setOpaque(true);
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLuuMousePressed(evt);
            }
        });
        jPanel3.add(btnLuu);
        btnLuu.setBounds(400, 450, 110, 50);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Giới Tính");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(210, 170, 90, 40);

        lbGioiTinh.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbGioiTinh.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbGioiTinh);
        lbGioiTinh.setBounds(330, 170, 120, 40);

        txtGioiTinh.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jPanel3.add(txtGioiTinh);
        txtGioiTinh.setBounds(330, 170, 120, 40);
        jPanel3.add(txtNgaySinh);
        txtNgaySinh.setBounds(130, 270, 190, 30);
        jPanel3.add(lbNgaySinh);
        lbNgaySinh.setBounds(130, 270, 190, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMiniMouseClicked
        this.setExtendedState(FORM_NHANVIEN.ICONIFIED);
    }//GEN-LAST:event_lbMiniMouseClicked

    private void lbMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMiniMouseEntered
        lbMini.setForeground(Color.BLACK);
        lbMini.setOpaque(true);
        lbMini.setBackground(Color.WHITE);
    }//GEN-LAST:event_lbMiniMouseEntered

    private void lbMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMiniMouseExited
        lbMini.setForeground(Color.WHITE);
        lbMini.setOpaque(false);
        lbMini.setBackground(new Color(61,145,106));
    }//GEN-LAST:event_lbMiniMouseExited

    private void lbCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMouseEntered
        lbClose.setForeground(Color.BLACK);
        lbClose.setOpaque(true);
        lbClose.setBackground(Color.WHITE);
    }//GEN-LAST:event_lbCloseMouseEntered

    private void lbCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMouseExited
        lbClose.setForeground(Color.WHITE);
        lbClose.setOpaque(false);
        lbClose.setBackground(new Color(61,145,106));
    }//GEN-LAST:event_lbCloseMouseExited

    private void lbCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbCloseMousePressed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void btnCapNhatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatMousePressed
        HienTextField();
         
        
       
        
        
        
           // Date date1 = f1.parse(lbNgaySinh.getText());
            //String ngaysinh = f.format(date1);
            //Date date2 = f.parse(ngaysinh);
            
           
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnCapNhatMousePressed

    private void btnLuuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMousePressed
        // TODO add your handling code here:
        if(new KiemTraLoi().KT_SDT(String.valueOf(txtSDT.getText()))==false)
        {
            JOptionPane.showMessageDialog(rootPane, "Số điện thoại không hợp lệ");
        }
        else if(String.valueOf(txtEmail.getText()).contains("@") == false)
        {
            JOptionPane.showMessageDialog(rootPane, "Email không hợp lệ");
        }
        else
        {
        SimpleDateFormat f = new SimpleDateFormat("yyyy/MM/dd");
        
        String NgaySinh = f.format(txtNgaySinh.getDate());
        
        int conf = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn lưu");
        if(conf == 0)
        {
            if(new BUS_SUA().capnhatTTNV(txtMaNV.getText(), txtHoTen.getText(), String.valueOf(txtGioiTinh.getSelectedItem()), NgaySinh, txtSDT.getText(), txtDiaChi.getText(), txtEmail.getText()))
            {
                ADMIN.LocListNV();
//                for(ThongTinNhanVien nv : listnv)
//                {
//                    nv.setHoTen(txtHoTen.getText());
//                    nv.setGioiTinh(String.valueOf(txtGioiTinh.getSelectedItem()));
//                    nv.setNgaySinh(NgaySinh);
//                    nv.setSDT(txtSDT.getText());
//                    nv.setDiaChi(txtDiaChi.getText());
//                    nv.setEmail(txtEmail.getText());
//                    
//                    
//                    listnv.add(nv);
//                }
            }
            
            SimpleDateFormat d = new SimpleDateFormat("dd/MM/yyyy");
            String date = d.format(txtNgaySinh.getDate());
            
            lbHoTen.setText(txtHoTen.getText());
            lbGioiTinh.setText(String.valueOf(txtGioiTinh.getSelectedItem()));
            lb.setText(date);
            lbSDT.setText(txtSDT.getText());
            lbDiaChi.setText(txtDiaChi.getText());
            lbEmail.setText(txtEmail.getText());
            
            
        }
        else
        {
            //JOptionPane.showMessageDialog(rootPane, "Không lưu");
        }
        HienLabel();  
        }
    }//GEN-LAST:event_btnLuuMousePressed
    int mx , my ;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mx, y-my);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        mx = evt.getX();
        my = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_NHANVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_NHANVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_NHANVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_NHANVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_NHANVIEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCapNhat;
    private javax.swing.JLabel btnLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lbClose;
    public static transient javax.swing.JLabel lbDiaChi;
    public static javax.swing.JLabel lbEmail;
    public static javax.swing.JLabel lbGioiTinh;
    public static javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbMini;
    public javax.swing.JLabel lbNgaySinh;
    public static javax.swing.JLabel lbSDT;
    public static javax.swing.JTextField txtDiaChi;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JComboBox<String> txtGioiTinh;
    public static javax.swing.JTextField txtHoTen;
    public static javax.swing.JLabel txtMaNV;
    public com.toedter.calendar.JDateChooser txtNgaySinh;
    public static javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
